# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the imbios/bun-node image as the base image with Node and Bun
# Keep bun and node version in sync with package.json
FROM imbios/bun-node:1.1.38-18-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install the root dependencies and devDependencies
RUN npm install

# Copy landing package.json and package-lock.json
COPY landing/package.json landing/package-lock.json ./landing/

# Install the landing dependencies and devDependencies
RUN cd landing/ && npm install

# Copy the entire project to the working directory
COPY . .

# Build the project
RUN npm run build

# Use a smaller base image for the final image
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# Define environment variables
ENV NODE_ENV=production

# Specify the command to run the MCP server
ENTRYPOINT ["node", "dist/index.js", "start", "$NEON_API_KEY"]
