import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { neon } from '@neondatabase/serverless';

const ENV_FILE = path.resolve(import.meta.dirname, '..', '.env.e2e');

async function provisionInstagresDb(): Promise<string> {
  const response = await fetch('https://instagres.com/api/v1/database', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ ref: 'mcp-server-neon-e2e-tests' }),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(
      `Instagres provisioning failed: ${response.status} ${body}`,
    );
  }

  const data: unknown = await response.json();
  if (
    typeof data !== 'object' ||
    data === null ||
    !('connection_string' in data) ||
    typeof data.connection_string !== 'string'
  ) {
    throw new Error('Instagres provisioning returned no connection_string');
  }

  return data.connection_string;
}

async function isDatabaseReachable(connectionString: string): Promise<boolean> {
  try {
    const sql = neon(connectionString);
    await sql`SELECT 1`;
    return true;
  } catch {
    return false;
  }
}

function readStoredConnectionString(): string | undefined {
  if (!existsSync(ENV_FILE)) {
    return undefined;
  }
  const content = readFileSync(ENV_FILE, 'utf-8');
  const dbMatch = content.match(/^OAUTH_DATABASE_URL=(.+)$/m);
  return dbMatch?.[1]?.trim();
}

function writeStoredConnectionString(connectionString: string): void {
  const envContent = [
    '# Auto-generated by e2e/provision-oauth-db.ts – do not commit',
    `OAUTH_DATABASE_URL=${connectionString}`,
    '',
  ].join('\n');
  writeFileSync(ENV_FILE, envContent);
}

export async function ensureOauthDatabaseUrl(): Promise<string> {
  const fromEnv = process.env.OAUTH_DATABASE_URL?.trim();
  if (fromEnv && (await isDatabaseReachable(fromEnv))) {
    return fromEnv;
  }

  const stored = readStoredConnectionString();
  if (stored && (await isDatabaseReachable(stored))) {
    return stored;
  }

  const connectionString = await provisionInstagresDb();
  writeStoredConnectionString(connectionString);
  return connectionString;
}
